//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazajGulf.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeCarousel
    {
        public int Id { get; set; }
        public string ShowHeading { get; set; }
        public string ShowDesc { get; set; }
        public string ShowTiming { get; set; }
        public string ShowImageUrl { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
