//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazajGulf.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestVideo
    {
        public int Id { get; set; }
        public string VideoDescription { get; set; }
        public string ReleaseData { get; set; }
        public string VideoUrl { get; set; }
        public string ThumbnailImage { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
